In [ ]:
my_list=[1,2,3]
my_list

[1, 2, 3]

Conversion to 1-D and 2-D array

In [ ]:
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
my_lists=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(my_lists)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#random numbers between 0 to 1
np.random.rand(4)

array([0.71416278, 0.02475422, 0.36623019, 0.74060165])

In [ ]:
np.random.rand(5,4)

array([[0.91748446, 0.8016552 , 0.98424473, 0.9536157 ],
       [0.15565244, 0.50359659, 0.31570272, 0.43153039],
       [0.63116379, 0.77179197, 0.84772161, 0.85159157],
       [0.13359257, 0.41122087, 0.36457341, 0.22049397],
       [0.49681916, 0.25596439, 0.36495642, 0.75318245]])

In [ ]:
# 0 centered
np.random.randn(3)

array([ 0.45329176,  2.69651417, -0.57737315])

In [ ]:
np.random.randn(4,5)

array([[-1.95259561,  0.83064963, -2.18190081,  0.11626179, -0.66401969],
       [-0.98354308, -0.82039732, -0.55394353,  0.82559856,  0.08037802],
       [-0.19870619,  1.46345522,  0.11408306, -0.75884155, -0.88747119],
       [-1.08939395,  1.40038829, -1.13826812,  0.67620751,  1.65619976]])

In [ ]:
np.random.randint(1,10)

9

In [ ]:
np.random.randint(1,100,10)

array([48, 62, 20, 42,  8, 93,  6, 40, 90, 18])

comparision of randint with arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.randint(1,10,10)

array([3, 2, 5, 7, 6, 3, 4, 3, 4, 7])

Reshape

In [ ]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
randomarr=np.random.randint(1,100,20)
randomarr

array([52, 31, 12, 94, 98, 71, 15, 84, 13, 90,  1, 72, 44, 35, 13, 30, 30,
       15, 59, 83])

In [ ]:
randomarr.max()

98

In [ ]:
randomarr.min()

1

In [ ]:
#Index of the maximum element
randomarr.argmax()

4

In [ ]:
#index of the minimum element
randomarr.argmin()

10

Shape of the vector or matrix

In [ ]:
arr=np.arange(0,25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#single vector
arr.shape

(25,)

In [ ]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
#data type of a values or array
arr.dtype

dtype('int64')

In [ ]:
#instead of writing the content we can put
from numpy.random import randint
randint(1,10,2)

array([2, 1])

**Numpy Indexing and selection**

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[3]

4

In [ ]:
# from 4th index to last
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#upto 4th index
arr[:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#broadcasting in numpy
arr[:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
slice_of_array=arr[0:6]
slice_of_array

array([100, 100, 100, 100, 100,   6])

In [ ]:
slice_of_array[:]=1000
slice_of_array

array([1000, 1000, 1000, 1000, 1000, 1000])

**The slice_of_array broadcast it is aslo reflecting the original arr, because slice_of_array is not a cpoy. it is  a reference**

In [ ]:
arr

array([1000, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [ ]:
arr_copy=arr.copy()
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [ ]:
arr_copy[:]=10000
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000])

In [ ]:
#changes in arr_copy not effectes the arr
arr

array([1000, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

Matrix with **Numpy**

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr_2d[0][0])
print(arr_2d[0])

1
[1 2 3]


In [ ]:
arr_2d[1,2] #use this notation

6

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr_2d[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
boolean_arr=arr>10
boolean_arr

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[boolean_arr]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1,1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

**Numpy Operations**

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
arr / 0

<ipython-input-65-db39a1c38901>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
<ipython-input-65-db39a1c38901>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
1/arr

<ipython-input-66-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
np.max(arr)

10

In [ ]:
np.min(arr)

0

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

Exercise

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.random.rand()

0.5421680259571955

In [ ]:
np.random.randn(25)

array([-0.85429092, -0.12877309,  0.41618737,  1.14200369,  0.96337822,
       -0.48793002,  0.30211819,  1.44893215,  3.22691262, -1.07195657,
       -0.77300309,  0.97782962,  0.45924656, -1.57183958,  0.69006529,
        1.88082786,  0.01548869, -0.14571315, -0.329958  , -1.34446415,
        1.00529993,  0.1726675 , -0.19010122,  0.70366809, -0.06935738])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()

325

In [ ]:
mat[1:5,0:5].sum()

310

In [ ]:
np.std(mat)

7.211102550927978

In [ ]:
mat.sum(axis=1) # horizontal

array([ 15,  40,  65,  90, 115])

In [ ]:
mat.sum(axis=0)#vertical

array([55, 60, 65, 70, 75])