In [1]:
import numpy as np
mylist=[1,2,3]
print(type(mylist))

arr=np.array(mylist)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
mat=np.array(mylist)

In [4]:
mat.shape

(3, 3)

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3))+4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [11]:
# in python may be error
[1,2,4] + 2

TypeError: ignored

In [12]:
[1,2,4] * 2

[1, 2, 4, 1, 2, 4]

In [13]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
# line space will give the numbers between them how many you need
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
# creating the identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# to get the random number between the 0 and 1 ( uniform distribution)
np.random.rand(1)

array([0.48448096])

In [18]:
np.random.rand(5,5)

array([[0.64849357, 0.63967181, 0.90903988, 0.20234707, 0.30438758],
       [0.75448755, 0.3515838 , 0.00866483, 0.79007686, 0.78646865],
       [0.15751407, 0.49083778, 0.76248201, 0.99789007, 0.658111  ],
       [0.68989682, 0.59597462, 0.03944988, 0.12165805, 0.74181593],
       [0.72592254, 0.13631002, 0.55463364, 0.46948126, 0.8873796 ]])

In [19]:
np.random.randn(2)

array([-0.65127921, -0.71561118])

In [20]:
np.random.randn(2,2)

array([[1.32417206, 0.08128373],
       [0.61299754, 1.19717391]])

In [21]:
# these are the random numbers between 1 and 100 , total 10 numbers
np.random.randint(1,100,10)

array([27, 77, 16, 22, 57, 68, 74, 91, 97, 16])

In [22]:
# the same seed values means each person or each time when we are using the same seed getting the same random numbers for every person
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.shape

(25,)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
rarr=np.random.randint(0,50,10)
rarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [28]:
rarr.min()

10

In [29]:
rarr.max()

48

In [30]:
# for getting the indexex of the min and max elements
print(np.argmax(rarr))
print(np.argmin(rarr))

1
6


In [31]:
# integer 64 bit
rarr.dtype

dtype('int64')

In [32]:
arr=np.arange(1,100,10)

In [33]:
arr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
arr[8]

81

In [35]:
arr[2:8]

array([21, 31, 41, 51, 61, 71])

In [36]:
arr[:7]

array([ 1, 11, 21, 31, 41, 51, 61])

In [37]:
arr[3:]

array([31, 41, 51, 61, 71, 81, 91])

In [38]:
arr+100

array([101, 111, 121, 131, 141, 151, 161, 171, 181, 191])

In [39]:
arr*10

array([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [40]:
# slicing
slice_arr=arr[:8]

In [41]:
slice_arr

array([ 1, 11, 21, 31, 41, 51, 61, 71])

In [42]:
slice_arr[:]=100

In [43]:
slice_arr

array([100, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,  81,  91])

In [45]:
slice_copy=arr.copy()
slice_copy

array([100, 100, 100, 100, 100, 100, 100, 100,  81,  91])

In [46]:
slice_copy[:8]=99

In [47]:
slice_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 81, 91])

In [48]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,  81,  91])

In [49]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr_2d[0]

array([1, 2, 3])

In [51]:
arr_2d[1][2]

6

In [52]:
arr_2d[1,2]

6

In [53]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [54]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr==2

array([False,  True, False, False, False, False, False, False, False,
       False])

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# added element by element
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [61]:
arr[0]=0


In [62]:
arr

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
1/arr

<ipython-input-63-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [64]:
arr/arr

<ipython-input-64-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sqrt(arr)

array([0.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [66]:
np.log(arr)


<ipython-input-66-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [67]:
np.sum(arr)

54

In [68]:
np.mean(arr)

5.4

In [69]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [70]:
arr_2d.shape

(3, 4)

In [71]:
arr_2d.sum(axis=0)

array([16, 19, 22, 25])

In [72]:
arr_2d.sum(axis=1)

array([10, 26, 46])